name = "DiplodocusTransport"
uuid = "f63b9913-7a9a-464d-82b9-3e1e536d6db0"
version = "0.2.0"
authors = ["Christopher Everett"]

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DiplodocusCollisions = "32d0d58a-4da0-4f8e-8b7e-c2816ac6e5cb"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Bessels = "0.2"
CUDA = "5.9"
DiplodocusCollisions = "0.2"
JLD2 = "0.6.2"
KernelAbstractions = "0.9"
LinearAlgebra = "1.10"
ProgressMeter = "1.10"
Revise = "3.8"
SparseArrays = "1.12"
Statistics = "1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
