name = "BoltzmannEquationSolver"
uuid = "f63b9913-7a9a-464d-82b9-3e1e536d6db0"
authors = ["Christopher Everett"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
BoltzmannCollisionIntegral = "20179301-8dfd-43f5-a10b-08fddd2c788a"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
Bessels = "0.2"
BenchmarkTools = "1"
BoltzmannCollisionIntegral = "2.0.2"
CairoMakie = "0.12.14, 0.13"
DifferentialEquations = "7.14.0"
DocumenterTools = "0.1.20"
LinearAlgebra = "1.10.0"
ProgressLogging = "0.1"
Statistics = "1"
RecursiveArrayTools = "3"
JLD2 = "0.5"
Tullio = "0.3.7"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
